const fs = require('fs');
const path = require('path');

const chainId = process.argv[2];

if (!chainId) {
    console.error("❌ Please provide a chainId! Example: node format_deployments.js 16602");
    process.exit(1);
}

const frontendPath = path.join(__dirname, '../frontend/deployments.json');

// Read temporary addresses
const tempPath = './temp_addresses.json';
if (!fs.existsSync(tempPath)) {
    console.error("❌ temp_addresses.json not found. Did you run `forge script` first?");
    process.exit(1);
}
const addresses = JSON.parse(fs.readFileSync(tempPath, 'utf8'));

// Read ABI generated by Forge (Only Agentra now)
const agentraArtifact = JSON.parse(fs.readFileSync('./out/Agentra.sol/Agentra.json', 'utf8'));

// Construct the master payload
let deployments = {};
if (fs.existsSync(frontendPath)) {
    const rawData = fs.readFileSync(frontendPath, 'utf8').trim();
    if (rawData) {
        try {
            deployments = JSON.parse(rawData);
        } catch (e) {
            console.warn("⚠️ deployments.json was malformed or empty. Overwriting with fresh JSON.");
            deployments = {};
        }
    }
}

// 1. Insert placeholder for the ABI
deployments[chainId] = {
    Agentra: {
        address: addresses.Agentra,
        abi: "%%AGENTRA_ABI%%"
    }
};

// 2. Format the overall structure nicely (2 spaces)
let outputJson = JSON.stringify(deployments, null, 2);

// 3. Swap the placeholder with the minified (single-line) ABI array
outputJson = outputJson.replace('"%%AGENTRA_ABI%%"', JSON.stringify(agentraArtifact.abi));

// Write the final clean JSON to the frontend
fs.writeFileSync(frontendPath, outputJson);
fs.unlinkSync('./temp_addresses.json'); // cleanup
console.log(`✅ Deployments auto-synced to frontend for Chain ID ${chainId} (with compact ABIs)`);